### ISSUE TITLE
How to test a function that returns a Promise

### ISSUE THREAD

**Issue by zhangchiqing** [davidchambers/doctest#70]
I want to test a function that returns a Promise
I expect this test case to fail, but it passed. Do I miss anything here?
```
// > resolve(2)
// Promise.resolve(3);
function resolve(x) {
  return Promise.resolve(x);
}
```

**Comment by davidchambers** [comment]
Thank you for the bug report, @zhangchiqing. The problem lies with [`R.equals`][1]. I just opened ramda/ramda#1616 for discussion.


[1]: http://ramdajs.com/docs/#equals

**Comment by danse** [comment]
I think that promises here should be considered as generic objects. Note that even in Python, doctests were never meant to compare two objects, since the semantic of such a comparison would be ambiguous. [Something loosely related here, from the Python doc](https://docs.python.org/2/library/doctest.html#warnings).

Interestingly enough, trying to work around this constraints would lead you to test with doctests just purely functional code, and push the use of promises elsewhere, at the boundaries of your computation logic. Promises are asynchronous because they usually involve side effects, which are out of the range of doctests anyway.

If you really need to test a function returning an object, you will need to provide equality methods for your object, like showed in comparisons for Python dictionaries, in the doc linked above

**Comment by zhangchiqing** [comment]
I agree. If we need to doctest a function that returns a generic Object (e.g. `MyObject` in your case), we could provide its own equality method. But that equality method would have to return a Bool value **synchronously** for doctest to check the result.

Since Promises are asynchronous, I don't think doctest is able to wait for the asynchronous operation to finish then check. (Please correct me if I'm wrong here)

I tried, this would fail.
```
// > resolve(2).then(function(x) { return x; })
// 2
function resolve(x) {
  return Promise.resolve(x);
}

// => || FAIL: expected 2 on line 32 (got {})
```

Then it would mean that a function returns a Promise, which is asynchronous, would be untestable for doctest. no?

**Comment by davidchambers** [comment]
> Then it would mean that a function returns a `Promise`, which is asynchronous, would be untestable for doctest. no?

Correct. Testing asynchronous functions is out of scope for this project.

Thanks for finding and reporting a bug in Ramda, though! I've opened a pull request to fix it.
