### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by sils** [davidchambers/doctest#71]
Any way to measure test coverage with this?

**Comment by davidchambers** [comment]
No.

It's important to view doctests as complementary to unit tests rather than as substitutes for unit tests. Unit tests ensure that code is correct; doctests ensure that examples in documentation remain up to date. Unit tests allow us to test all the edge cases, whereas in documentation it's best to demonstrate the most common use cases.

The combination I most commonly use for unit testing is [Mocha][1] + [Istanbul][2].


[1]: http://mochajs.org
[2]: https://gotwarlost.github.io/istanbul/

**Comment by sils1297** [comment]
Well I usually want the combination of coverage for doctests and unittests
because I otherwise have redundancy in my tests. (Not saying you should
doctest everything.)

**Comment by davidchambers** [comment]
Is the idea that the coverage tool would highlight the behaviour not covered by your usage examples? This had not occurred to me. I can imagine this being useful.

If there's some way for us to integrate with Istanbul I'm open to doing so. I'll happily provide guidance and review a pull request if you or anyone else is interested in working on this feature.

**Comment by sils1297** [comment]
Coverage would either show behaviour not covered by the examples or allow us to reach full coverage when combining unittests and doctests so we don't have to duplicate doctests as unittests.

**Comment by danse** [comment]
From my experience using doctests, usually what is desired is to have a coverage report which takes into account both unit tests and doctests. I'm not sure about how to implement this though.

I guess that the idea would be to instrument the code before running the doctests, and somehow keep a state about the part of the code already covered, then run the unit tests so that further coverage is recorded. This doesn't sound easy. If the price to pay is a more complex interface for the doctest user, this is probably not worth it

**Comment by davidchambers** [comment]
Overlap between doctests and unit tests is desirable. Usage examples often only cover the common cases, whereas unit tests should also cover the edge cases. Unit tests which mirror doctests are still valuable: unit tests can also serve as documentation, but unit tests which test edge cases exclusively are less approachable.
